[project]
name = "arm-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ansible>=8.7.0",
    "ansible-core>=2.15.13",
]
