---
model: opi
serial: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63333539623531326533643536326462343234393162313364333963353632386633353839376433
          3137353162623930333134643734353335626538613634370a633232376531346336623662313136
          66656338343534363433643263323561353437386565363938343635353466323764313563303932
          3931333333313636330a306365383631356138303033366335623935616336643362633035613561
          32396635366334316333656361336134633434373432306534373430363764313535636364623136
          3932656134343066623033313239323631396266393631373761
tailscale_state: absent
hostname: "f0a441a6"
ts_auth_key: "tskey-auth-km3Gvjw1UA11CNTRL-MG2X1gnddNf2gcTHDVxENfoaZcGXu5fN"
roles:
  - common
  - kvm
  - avm
  # - tailscale
