---
model: opi
serial: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63333539623531326533643536326462343234393162313364333963353632386633353839376433
          3137353162623930333134643734353335626538613634370a633232376531346336623662313136
          66656338343534363433643263323561353437386565363938343635353466323764313563303932
          3931333333313636330a306365383631356138303033366335623935616336643362633035613561
          32396635366334316333656361336134633434373432306534373430363764313535636364623136
          3932656134343066623033313239323631396266393631373761
# tailscale_state: absent
hostname: "sudeep-avm"
# ts_auth_key: ""
ts_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37333035316532333938666166396631646561623436333735353762666330363036386330373464
          6333616530376639356365653361643431633034626365360a376363356666396465303661656261
          66336133393366363839363735663161326266613766343262633632356365623738313433383834
          3762303635323261640a313430656538623263323363383737636563636332396432636334636166
          66653839376361613732656364653264333536306535323236666564306539303266623463396339
          63613065643534343639646339663261626664343833336536656262303766356232656462396261
          336166393833333333333931333030613436
roles:
  - common
  - kvm
  - avm
  - tailscale
