---
model: opi
serial: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63333539623531326533643536326462343234393162313364333963353632386633353839376433
          3137353162623930333134643734353335626538613634370a633232376531346336623662313136
          66656338343534363433643263323561353437386565363938343635353466323764313563303932
          3931333333313636330a306365383631356138303033366335623935616336643362633035613561
          32396635366334316333656361336134633434373432306534373430363764313535636364623136
          3932656134343066623033313239323631396266393631373761
tailscale_state: absent
hostname: "sudeep-avm"
# ts_auth_key: ""
ts_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33346231623463373739393532396362386231356639316530623034626165663030653337323435
          3539666638626433303331303861353437353833656632650a393064643361656635323166636535
          30626663333662333638356437303636643666333936386239323738366437663530633030623135
          3365353038633033320a363837353035613332306435306435633738316630373031363539653239
          35363730366165353062323433303733613361396361383630653234643761393736353164303762
          61346234343030653339653037323337326362613265613965636433303562336331623963653238
          646236303130383839353230643138623830
roles:
  - common
  - kvm
  - avm
  - tailscale
