---
# Global variables for all hosts
ansible_user: pi
github_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65333466636462643636383134303465366335336238666133313061303135613234373739326233
          6466616638366233633036666237613466646235653232360a613434663431663338386664626333
          63323939666464376539386135336337663065386439343237326361306563373735623038333565
          6261353737326465610a336462653839393138393362626564353637333831316435306263373936
          31663835336566386332393932663932623738343534353739303234663364623230656438623364
          64656639366161323630363635376434666464393861303434336666626461366264333163643165
          37356465373962383035386430386333303539356333633337396330346639333330363632363663
          66656466623330396332623734626138383466636232353665643863333238373739393236303163
          3236